"""Generate C++ header with link lengths and body mounts."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _fmt_float(value: float | None, *, comment: str = "") -> str:
    if value is None:
        base = "0.0f  /* MISSING — fill after CAD extract */"
    else:
        base = f"{float(value):.4f}f"
    if comment:
        return f"{base}  /* {comment} */"
    return base


def _fmt_vec3(values: list[float]) -> str:
    return (
        "{"
        + ", ".join(f"{float(v):.6f}f" for v in values)
        + "}"
    )


def render_kinematics_header(model: dict[str, Any]) -> str:
    lengths = model.get("lengths_mm") or {}
    meta = model.get("meta") or {}
    generated_at = meta.get("generated_at", "unknown")
    yaw_unit = meta.get("yaw_unit", "deg")
    mounts = sorted(
        model.get("body_mounts") or [],
        key=lambda m: int(m.get("leg_id", 0)),
    )
    femur_approx = bool(model.get("femur_synthesized_approximate"))
    datasheet = model.get("servo_datasheet") or {}
    axis_len = datasheet.get("axis_length_mm", 42.9)

    femur_comment = ""
    if femur_approx:
        femur_comment = f"approx: MG996R height {axis_len} mm datasheet"
    elif model.get("femur_source") == "override":
        femur_comment = "from femur_override_length_mm"

    yaw_name = "LEG_MOUNT_YAW_DEG" if yaw_unit == "deg" else "LEG_MOUNT_YAW_RAD"

    origins = ["{0.0f, 0.0f, 0.0f}"] * 6
    yaws = ["0.0f"] * 6
    axes = [
        "{{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 1.0f}}"
    ] * 6

    for mount in mounts:
        leg_id = int(mount["leg_id"])
        if leg_id < 0 or leg_id > 5:
            continue
        origins[leg_id] = _fmt_vec3(mount["origin_mm"])
        yaws[leg_id] = f"{float(mount['yaw']):.6f}f"
        axes[leg_id] = (
            "{"
            + ", ".join(
                [
                    _fmt_vec3(mount["axis_x"]),
                    _fmt_vec3(mount["axis_y"]),
                    _fmt_vec3(mount["axis_z"]),
                ]
            )
            + "}"
        )

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by hexapod_kinematics extractor — do not edit",
        f"// generated_at: {generated_at}",
        f"// yaw_unit: {yaw_unit}",
        "",
        f"constexpr float COXA_LENGTH = {_fmt_float(lengths.get('coxa'))};",
        f"constexpr float FEMUR_LENGTH = {_fmt_float(lengths.get('femur'), comment=femur_comment)};",
        f"constexpr float TIBIA_LENGTH = {_fmt_float(lengths.get('tibia'))};",
        (
            "constexpr float FOOT_PAD_PROTRUSION_MM = "
            f"{_fmt_float((model.get('foot_pad') or {}).get('protrusion_mm'), comment='RF-F12050 5mm - 3mm recess')};"
        ),
        (
            "constexpr float TIBIA_EFFECTIVE_LENGTH = "
            f"{_fmt_float(lengths.get('tibia_effective'), comment='TIBIA_LENGTH + FOOT_PAD_PROTRUSION_MM')};"
        ),
        "",
        "constexpr float LEG_MOUNT_ORIGIN[6][3] = {",
        "    " + ",\n    ".join(origins) + ",",
        "};",
        "",
        f"constexpr float {yaw_name}[6] = {{",
        "    " + ", ".join(yaws) + ",",
        "};",
        "",
        "// LEG_MOUNT_AXES[leg][axis][xyz] where axis 0=X, 1=Y, 2=Z (servo)",
        "constexpr float LEG_MOUNT_AXES[6][3][3] = {",
        "    " + ",\n    ".join(axes) + ",",
        "};",
        "",
    ]
    return "\n".join(lines)


def write_kinematics_header(model: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_kinematics_header(model), encoding="utf-8")
    return path


# Backwards-compatible aliases
def render_link_lengths_header(model: dict[str, Any]) -> str:
    return render_kinematics_header(model)


def write_link_lengths_header(model: dict[str, Any], path: Path) -> Path:
    return write_kinematics_header(model, path)
